"""empty message

Revision ID: 2daca1302979
Revises: aa812ac1ec69
Create Date: 2023-09-04 17:26:38.441049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daca1302979'
down_revision: Union[str, None] = 'aa812ac1ec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userename', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'userename')
    # ### end Alembic commands ###
