"""empty message

Revision ID: 5857139642e2
Revises: 6bf35b48d8c3
Create Date: 2023-09-04 17:22:49.124797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5857139642e2'
down_revision: Union[str, None] = '6bf35b48d8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
